#!/usr/bin/env ruby

require 'yaml'

data = YAML.load(File.read('data/games.yml'))

list = data.map { |g| [ g['gm'], g['contact'] ] }.uniq

puts 'GMs running games'

list.each { |g| puts "#{g[0]}: #{g[1]}" }
